index.js, matchExported.js, package.json, yarn.lock
This is a temporary release while we wait for a new update of babel-normalize-comments.
=> 0.3.0 beta

index.js
- `BooleanLiteralTypeAnnotation`
- `NullLiteralTypeAnnotation`
=> Add new types

.prettierrc, __snapshots__/test.js.snap, index.js, kinds.js, package.json, test.js, yarn.lock
Apologies, but adding prettier got added here. Running prettier before it was project-added broke the comment flow types.
=> parse external files

packages/extract-react-types/__snapshots__/test.js.snap, packages/extract-react-types/src/index.js, packages/extract-react-types/test.js
I noticed these corner cases in my own work. Likely you should add a test for Flow/decorators combination too.
Closes #53.
=> Support decorators + fix issue related to custom props in functions

.changeset/4298a628/changes.json, .changeset/4298a628/changes.md, packages/extract-react-types/__snapshots__/test.js.snap, packages/extract-react-types/src/index.js, packages/extract-react-types/src/kinds.js, packages/extract-react-types/test.js, packages/kind2string/src/index.js, packages/kind2string/test.js
=> Add logical expression operator

.changeset/0fcb46d3/changes.json, .changeset/0fcb46d3/changes.md, .eslintrc.js, .flowconfig, jest.config.js, package.json, packages/kind2string/package.json, packages/pretty-proptypes/package.json, yarn.lock
I wanted to stop having problems with testing and builds so I added preconstruct. Thanks @mitchellhamilton
=> add preconstruct

.changeset/gold-scissors-hammer/changes.json, .changeset/gold-scissors-hammer/changes.md, packages/pretty-proptypes/src/PrettyConvert/converters.js
I was looking at things and found that this wasn't updated because this file has an eslint disable comment and I used an eslint plugin to codemod things.
=> Fix a usage of the css prop that wasn't updated to emotion 10's syntax

.changeset/long-vans-lay/changes.json, .changeset/long-vans-lay/changes.md, packages/kind2string/src/index.js, packages/kind2string/src/utils.js
Reopens this pr: https://github.com/atlassian/extract-react-types/pull/88
=> feat: option to hide errors

.changeset/yellow-cherries-protect.md, packages/kind2string/src/index.js, packages/kind2string/test.js
fixes: https://github.com/atlassian/extract-react-types/issues/100
=> exports converters from kind2string package

.changeset/late-rabbits-clap.md, packages/extract-react-types/src/findExports.js, packages/extract-react-types/src/index.js
Refactors some methods in the `index.js` file to make it a little easier to grok.
=> Some minor refactoring

.changeset/beige-yaks-nail.md, packages/pretty-proptypes/src/Prop/Heading.js, packages/pretty-proptypes/src/PropType/index.js, packages/pretty-proptypes/src/Props/Wrapper.js, packages/pretty-proptypes/src/PropsTable/PropRow.js, packages/pretty-proptypes/src/PropsTable/index.js, packages/pretty-proptypes/src/index.js
<PropTable/> component added to pretty-proptype exports. 
minor bump
=> Pretty proptypes table

.changeset/smooth-ligers-fly.md, packages/pretty-proptypes/src/Props/index.js
fix a dumb dumb on my end.
Should fix the silly table head we're currently seeing in ak/docs
=> Remove table heads

.changeset/cool-sloths-shake.md, .changeset/stale-turkeys-buy.md, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js, packages/extract-react-types/src/kinds.js, packages/kind2string/src/index.js, packages/kind2string/src/utils.js, packages/kind2string/test.js
- Add support for TSTypeQuery
This fixes #113
=> Add support for TSTypeQuery

.github/workflows/release.yml
This will enable automatic versioning publishing on merge to master via changesets
=> 🔧 Update changeset action to autorelease

.changeset/dirty-dingos-exercise.md, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js
=> Support forwardRef typed via TypeScript type arguments (Generics)

packages/extract-react-types/__snapshots__/converters-flow.test.js.snap, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-flow.test.js, packages/extract-react-types/converters-typescript.test.js
Just some minor test clean up
- Tests now denote the typesystem
=> Test cleanup

.changeset/three-camels-end.md, packages/extract-react-types/src/index.js
=> Rename temporary variable 

.changeset/shiny-dolls-kiss.md, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js
=> 🐛 Fixes variable name clash bug

.changeset/tough-crews-share.md, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/converter.js, packages/extract-react-types/src/utils.js
=> ✨ Adds support for React.FC & FC

.github/workflows/node.js.yml, .github/workflows/test.yml
Github action to replace Travis CI
=> Add CI workflow

.changeset/seven-rats-taste.md, packages/extract-react-types-loader/index.js
As per #195. Should be marked as major bump for package release.
=> Remove Atlaskit specific process.env switches (#195)

.changeset/sour-houses-share.md, packages/pretty-proptypes/CHANGELOG.md, packages/pretty-proptypes/package.json
Reverts atlassian/extract-react-types#215
=> Revert "Version Packages"
