atlassian/extract-react-types

__snapshots__/test.js.snap, index.js, test.js
- The `props` property of `kind: object` has been renamed to `method`. THIS IS A MASSIVE BREAKING CHANGE
- added `typeParameters` converter
- rewrote genericTypeAnnotation to return `kind: generic` THIS IS A MASSIVE BREAKING CHANGE
- added `ObjectTypeSpreadProperty` converter
- stopped adding converters that were accepting not node.
=> Update kinds and add converters

__snapshots__/test.js.snap, index.js, test.js
Adding defaultProp support for React Elements. The following converters have been added: 
- JSXElement
- JSXOpeningElement
- JSXMemberExpression
- JSXIdentifier
- JSXExpressionContainer 
- JSXAttribute
=> Adding defaultProp support for React Elements

matchExported.js, package.json, yarn.lock
The format function in babel-log was removed in v2. I've replaced it with it's replacement within babel-log, ast-pretty-print.
=> Replace non-existent format babel-log function with ast-pretty-print

__snapshots__/test.js.snap, index.js, package.json, test.js
Change `ObjectTypeProperty` to convert keys instead of assuming they are an identifier and just applying the name.
NB: This is a breaking change to consumers
=> Parse object key

__snapshots__/test.js.snap, index.js, test.js
These are needed for the Atlaskit CalendarStateless prop documentation.
=> Add new converters and preserve reference names when converting identifiers in value mode

__fixtures__/test.json, __snapshots__/test.js.snap, index.js, test.js
JSON files are now detected and intentionally not parsed when imported as parsing them throws errors.
Also fix context not being passed through for the default props converter
=> Handle importing JSON files

__snapshots__/test.js.snap, index.js, kinds.js, test.js
Desired support:
```js
type Foo<T> = () => T;
class Component extends React.Component<{ a: Foo<string> }> {}
```
([AST Explorer for this example](https://astexplorer.net/#/gist/b5fd8296d03aadb48a9decfba5492c83/587c8ee8ea5713e4dcd0ae80731b19198fbeedba))
Output:
```js
Missing converter for: TypeParameterDeclaration
at convert (index.js:1032:25)
at Object.<anonymous>.converters.Identifier (index.js:661:51)
at convert (index.js:1033:16)
at Object.<anonymous>.converters.GenericTypeAnnotation (index.js:496:18)
at convert (index.js:1033:16)
at Object.<anonymous>.converters.FunctionTypeAnnotation (index.js:731:22)
at convert (index.js:1033:16)
at Object.<anonymous>.converters.TypeAlias (index.js:673:10)
at convert (index.js:1033:16)
at Object.<anonymous>.converters.Identifier (index.js:661:51) …
```
=> add support for TypeParameterDeclaration and TypeParameter

.changeset/8ac6319d/changes.json, .changeset/8ac6319d/changes.md, packages/extract-react-types/__snapshots__/test.js.snap, packages/extract-react-types/src/index.js, packages/extract-react-types/test.js
Passes `all=true` option to flow plugin as defined in babel-parser docs [here](https://babeljs.io/docs/en/next/babel-parser.html#plugins-options). Doing so enables the callable generics syntax `<T>(param: T) => T` defined in the [flow docs](https://flow.org/en/docs/types/generics/#toc-function-types-with-generics).
Here's an [example](https://github.com/uber-web/baseui/pull/1241/files#diff-e97b72fdc901df1b6ce8aa0c327e7a3eR154) of how i'm using this in my application code. Below is the error thrown when `extract-react-types-loader` fails to parse
```
4:32:59 PM: Failed to compile.
4:32:59 PM: ../src/block/block.js (../node_modules/extract-react-types-loader!../src/block/block.js)
4:32:59 PM: SyntaxError: /opt/build/repo/src/block/block.js: Unexpected token (154:64)
4:32:59 PM:   152 | } …
```
=> enables flow callable generics syntax

.changeset/silver-dots-exercise/changes.json, .changeset/silver-dots-exercise/changes.md, packages/extract-react-types/__snapshots__/test.js.snap, packages/extract-react-types/src/index.js, packages/extract-react-types/test.js
Adds support for TypeScript's `as` expression.
In TypeScript you can encounter the following scenario when using `union` strings.
```typescript
type Foo = 'foo' | 'bar';
interface Props {  bar: Foo; }
const foo: string = 'foo';
const props: Props = {
bar: foo as Foo,
}
```
Which yields an error: `Type 'string' is not assignable to type 'Foo'.`
In React this scenario occurs when you have union-typed props and you assign a static string value as a default value:
```typescirpt
type Foo = 'foo' | 'bar';
class Component extends React.Component<{ a: Foo }> {
static defaultProps = {
a: 'foo' as Foo,
}
}
```
=> Handle type casting in TypeScript (as)

.changeset/two-impalas-compare/changes.json, .changeset/two-impalas-compare/changes.md, packages/extract-react-types/src/index.js
This PR is a temporary workaround for this issue: https://github.com/atlassian/extract-react-types/issues/89
=> Workaround for null typescript definitions

.changeset/poor-maps-hang/changes.json, .changeset/poor-maps-hang/changes.md, packages/extract-react-types/src/index.js
It's possible for members not to exist on the value object. 
Added a check to ensure it doesn't throw
=> ensure members exist before attempting to filter

.changeset/three-rats-begin/changes.json, .changeset/three-rats-begin/changes.md, packages/pretty-proptypes/src/PrettyConvert/converters.js
This is causing a ruckus on the atlaskit/website, changing to a console.warn for now
=> change console.error to console.warn

.changeset/late-badgers-poke/changes.json, .changeset/late-badgers-poke/changes.md, packages/extract-react-types/__snapshots__/test.js.snap, packages/extract-react-types/src/index.js, packages/extract-react-types/src/kinds.js, packages/extract-react-types/test.js
Adds support for the `unknown` type
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type
https://github.com/atlassian/extract-react-types/issues/111
Todo:
=> ✨ Add support for TSUnknown

.changeset/hip-wasps-lay/changes.json, .changeset/hip-wasps-lay/changes.md, packages/extract-react-types/__fixtures__/component.tsx, packages/extract-react-types/__fixtures__/componentB.tsx, packages/extract-react-types/__snapshots__/test.js.snap, packages/extract-react-types/src/findExports.js, packages/extract-react-types/src/index.js, packages/extract-react-types/test.js
What it says on the tin. 
We now have logic for resolving a file with 
```jsx
export { default } from './x' 
```
to its relevant react component and types
=> Follow export { default } 

.changeset/eighty-months-smile.md, packages/pretty-proptypes/src/Props/Props.test.js, packages/pretty-proptypes/src/getPropTypes.js
- add generic proptype interface handling for such cases:
```typescript
interface FormProps<FormData> {
children: () => ReactNode;
onSubmit: OnSubmitHandler<FormData>;
/* When set the form and all fields will be disabled */
isDisabled?: boolean;
}
function Form<FormData extends Record<string, any> = {}>(
props: FormProps<FormData>,
) {}
```
=> feat(pretty-proptypes): handle generic prop typings

.changeset/eleven-lies-help.md, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js
Closes: #136  
Adds support for `React.FC<Props>`.
=> React.FC support

.changeset/smooth-moons-cheer.md, packages/pretty-proptypes/src/PropsTable/index.js
Add a missing jsx pragma and jsx import to a file which was missing it and trying to use emotion's css prop. This was resulting in an erroneous css attribute being rendered:
=> Add jsx pragma

.changeset/healthy-onions-design.md, package.json, packages/extract-react-types/__snapshots__/converters-flow.test.js.snap, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-flow.test.js, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js
- Reduced the amount of javascript being snapshotted by jest
- Adds `test:watch` command
- Cleans up core logic. Combining duplicate conditions, formatting etc.
=> DST-1321 test and logic clean up

.changeset/wise-bulldogs-repeat.md, packages/babel-plugin-extract-react-types/index.js, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js, packages/kind2string/src/index.js
Closes: #141
Adds the ability to 'ignore' a property in the case that you want to avoid a ["missing converter error"](https://github.com/atlassian/extract-react-types/issues/150)
To ignore a property, simply prefix the prop with a comment, which includes `@ert-ignore`.
```diff
interface FooProps {
-  // Docs about the bar property here
+  // @ert-ignore Docs about the bar property here
bar: unknown; 
}
const Foo = props => null;
```
=> DST-1321 Prop opt out

.changeset/shiny-cows-share.md, packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/findExports.js, packages/extract-react-types/src/index.js
Closes: #158 
Adds improved support for `memo` and `forwardRef` typed with generics ✨ 
This means ERT can now work with the following use cases: 
```tsx
import React, { forwardRef, memo } from 'react';
type MyComponentProps = {
foo: string,
}
const MyComponent = memo<MyComponentProps>((props, ref) => {
return <span>Foo</span>;
});
export default MyComponent;
```
and
```tsx
import React, { forwardRef, memo } from 'react';
type MyComponentProps = {
foo: string,
}
const MyComponent = memo<MyComponentProps>(forwardRef<HTMLElement, MyComponentProps>((props, ref) => {
return <span>Foo</span>;
}));
export default MyComponent;
```
=> ✨ Add support for memo typed with generics

packages/extract-react-types/__snapshots__/converters-typescript.test.js.snap, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/index.js
=> ✨ forwardRef wrapped in a memo now works with type inference

.changeset/afraid-socks-give.md, packages/pretty-proptypes/src/HybridLayout/PropEntry.js, packages/pretty-proptypes/src/HybridLayout/index.js, packages/pretty-proptypes/src/PropType/index.js, packages/pretty-proptypes/src/Props/index.js, packages/pretty-proptypes/src/PropsTable/index.js, packages/pretty-proptypes/src/components/constants.js, packages/pretty-proptypes/src/index.js, stories/FlowComponent.js, stories/TypeScriptComponent.tsx, stories/layout/Default.stories.js, stories/layout/Hybrid.stories.js, stories/layout/Table.stories.js
Adding a new hybrid layout for `pretty-proptypes` as well as some stories for the different layouts.
What it looks like by default: 
What it looks like with `@atlaskit/css-reset`:
=> New hybrid layout

.changeset/seven-laws-deliver.md, packages/extract-react-types/converters-typescript.test.js, packages/extract-react-types/src/converter.js, stories/TypeScriptComponent.tsx
Fix for [DST-2574](https://product-fabric.atlassian.net/browse/DST-2574).
Allows the proper conversion of keys in Typescript types that are written using quotes.
**NOTE:** Flow types aren't fixed by this. They render weirdly but in a different way – they show the quotes around the prop name.
=> Add typescript support for quoted keys in types

packages/pretty-proptypes/src/PropsTable/PropRow.js
@danieldelcore there was one more linting error your fix didn't catch 🥲
=> Fix linting error on unused `required`

.changeset/fifty-apples-marry.md, .changeset/pretty-carrots-raise.md, packages/pretty-proptypes/src/PropType/index.js, stories/FlowComponent.js, stories/TypeScriptComponent.tsx
=> Exclude types with comments

.changeset/fifty-carrots-hope.md, packages/babel-plugin-extract-react-types/__snapshots__/index.test.js.snap, packages/babel-plugin-extract-react-types/index.js, packages/babel-plugin-extract-react-types/index.test.js, packages/pretty-proptypes/src/HybridLayout/index.js, packages/pretty-proptypes/src/LayoutRenderer/index.js, packages/pretty-proptypes/src/PrettyConvert/AddBrackets.js, packages/pretty-proptypes/src/Prop/index.js, packages/pretty-proptypes/src/Props/index.js, packages/pretty-proptypes/src/PropsTable/PropRow.js, packages/pretty-proptypes/src/PropsTable/index.js, packages/pretty-proptypes/src/renderPropType.js, packages/pretty-proptypes/src/types.js, stories/layout/LayoutRenderer.stories.js, stories/layout/Permalink.stories.js
Allows permalinks to be rendered as each prop displays.
Loom demo: https://www.loom.com/share/85edd8c9a0a2435dba5cff7989651ed0
The demo above was recorded before the correct colour was given by design, so this is a more accurate screenshot of what the final experience can look like:
Of course, when `LayoutRenderer` is used it's entirely up to the developer to handle styles to whatever visual they want to achieve.
=> Prop table permalink

.changeset/angry-pets-hammer.md, packages/pretty-proptypes/src/HybridLayout/index.js, packages/pretty-proptypes/src/Prop/Heading.js, packages/pretty-proptypes/src/Prop/index.js, packages/pretty-proptypes/src/renderPropType.js, packages/pretty-proptypes/src/types.js, stories/TypeScriptComponent.tsx, stories/layout/LayoutRenderer.stories.js
Added deprecated styling onto deprecated props in
- Default layout
- Hybrid layout
- LayoutRenderer (most styles were added in the story example)
=> Add deprecated styling on deprecated props

.changeset/twenty-sheep-tie.md, packages/pretty-proptypes/src/HybridLayout/index.js, packages/pretty-proptypes/src/LayoutRenderer/index.js, packages/pretty-proptypes/src/LayoutRenderer/index.test.js, stories/layout/Hybrid.stories.js, stories/layout/LayoutRenderer.stories.js
Adds two props to LayoutRenderer:
- **sortProps:** provide a comparison function and it'll be used to sort the props displayed by LayoutRenderer
- **requiredPropsFirst:** Explicit support for the most common sorting approach; will put required props first
If both are used, the custom sort is done first, and then required props are sorted to the top.
I have not added support in the non-LayoutRenderer views in `pretty-proptypes`, as they're likely to be moved to LayoutRenderer in future.
=> Add "sortProps" and "requiredPropsFirst" props to LayoutRenderer

.changeset/tall-yaks-matter.md, packages/pretty-proptypes/src/LayoutRenderer/index.js, packages/pretty-proptypes/src/Props/index.js, packages/pretty-proptypes/src/PropsTable/index.js, packages/pretty-proptypes/src/utils.js
Through some intense debugging 😅 I realised the current output from the converter in `packages/extract-react-types/src/converter` already includes the information about the identifier declaring the props. See image below:
Given the very limited testing for this section of the code I had to go seriously defensive with any changes, so it should work under the expected object formats, falling back to an (expected) `undefined` display name values (already handled in code, [from my previous PR](https://github.com/atlassian/extract-react-types/pull/224/))
Not exactly ergonomic ... 😅 but I managed to test this by changing the source under `node_modules` for my atlassian-frontend installation and can confirm it's working as intended.
=> Alternatively obtain componentDisplayName from props object

package.json
**Why?**
This avoids a possible vuln where someone might publish malicious code to npm using this package name and it is accidentally installed by an unsuspecting developer.
=> remove root package name from project package.json

.changeset/clever-games-happen.md, packages/extract-react-types/src/converter.js
Adds null checks as there are cases when accessing .name falls with a Cannot read properties of undefined (reading 'name') error.
The original error was found during the build of Atlassian's Atlaskit website.
```
"  ╰─▶   × TypeError: Cannot read properties of undefined (reading 'name')\n" +
'        │     at converters.TSIndexedAccessType (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:974:30)\n' +
'        │     at convert (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1877:16)\n' +
'        │     at converters.TSTypeAnnotation (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1185:10)\n' +
'        │     at …
```
=> Fix Cannot read properties of undefined (reading 'name') for Indexed Types 

.changeset/wise-trains-run.md, packages/extract-react-types-loader/package.json, packages/kind2string/package.json, packages/pretty-proptypes/package.json
New version seems to be unable to publish because we used the not-yet-published version as a dependency for other packages:
https://github.com/atlassian/extract-react-types/actions/runs/16161623084/job/45614268679
=> Rollback version bump
